#!/usr/bin/env bash
if ! [ -d node_modules ]; then
  # elm-pages will crash with a vague error if elm-codegen is not in PATH.
  npm install
fi
npx --no -- elm-pages run ./scripts/src/CodeGenOpenApi.elm
