openapi: 3.0.0
info:
    title: Nullable enum
    version: 1.0.0
paths:
    "/":
        get:
            summary: Does stuff
            responses:
                200:
                    description: Ok
                    content:
                        application/json:
                            schema:
                                "$ref": "#/components/schemas/NullableEnum"
components:
    schemas:
        NullableEnum:
            type: string
            nullable: true
            enum:
                - Red
                - Blue
                - null
        Color:
            type: string
            enum:
                - Red
                - Blue
