#!/usr/bin/env bash
set -e
cache=$HOME/.elm/0.19.1/packages/mpizenberg/elm-placeholder-pkg/1.0.0
rm -rf "$cache"
mkdir -p "$cache"
ln -s "$PWD/elm-open-api-codegen/elm.json" "$cache/elm.json"
ln -s "$PWD/elm-open-api-codegen/src" "$cache/src"
rm -rf elm-open-api-codegen/.elm-pages example-using-api/.elm-pages
sed -i -e 's#"wolfadex/elm-open-api-codegen"#"mpizenberg/elm-placeholder-pkg"#' elm.json
sed -i -e 's#"wolfadex/elm-open-api-codegen"#"mpizenberg/elm-placeholder-pkg"#' example-using-api/scripts/elm.json
